### PR TITLE
fix: ensure git diff output is properly encoded as UTF-8

### LINKED ISSUE #26: UTF-8 Characters in Diff causing errors
Sample file:
[test.txt](https://github.com/user-attachments/files/19430269/test.txt)

Error:

```
Why are you making this change? (Press Enter to skip)

Sending diff to Claude...
Error: source sequence is illegal/malformed utf-8
```

### PR DESCRIPTION
**Pull request by milarze**
Fixes #26

### CODE REVIEW

File: spec/committer/commit_generator_spec.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@
 require 'committer/commit_generator'
 
 RSpec.describe Committer::CommitGenerator do
-  let(:diff) { load_fixture('sample_diff.txt') }
```
Comment (billybonks) [inline spec/committer/commit_generator_spec.rb:7]: i think sample diff is only used here so if you removed it we can delete the file

**Review by billybonks — CHANGES_REQUESTED** [review]

**Review by billybonks — APPROVED** [review]
